controllerの画面追加
INIAD-Developers/Mugen-sweeper pull request #44
Opened 2023-08-21 19:20 UTC by yossuli

## 内容

controllerの画面部分用のコンポーネント作成

## 変更点

コミットメッセージの通りです

## スクリーンショット・動画など

![スクリーンショット (66)](https://github.com/INIAD-Developers/Mugen-sweeper/assets/131968633/1895590a-f8b8-4492-8244-603ac149d2d7)

2023-08-21 21:05 UTC, bondrewd-iniad requested changes

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/Button/index.page.tsx
> +  className: string;
OSSではない内部向けコンポーネントで無限の自由度を与えると参照先を破壊しないように後から仕様変更することが困難になる

ゲーム全体のデザインを維持したままコンポーネント作者として意図した拡張プロパティのみを公開する

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/Button/index.page.tsx
> +  <button className={`${className} ${styles.button} `} onClick={onClick}>
無駄な空白消す

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.module.css
> +  background: url('./../../../public/images/icons.png') no-repeat;
`~/public...` で指定できない？

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +import type { BoardModel, Pos } from 'src/pages/game/index.page';
仕様記述の中心である型をページコンポーネントからexportしない

src/types/fuga.ts などに集約する

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +  }, [player]);
オブジェクトを依存配列に渡すと、Playerのアイデンティティが同一でもオブジェクトが更新されるとuseEffectが再度発火してPosが初期化されるように見えるが意図通りか？

`[player.x, player.y]` だと座標の変化のみに依存できる

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +  const displayPos = (): Pos | undefined => {
if (currentPlayerPos && board... でundefinedを返さないようにできないか？

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +  };
useMemoを使う

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/pages/controller/index.page.tsx
> +export type OpenCellModel = { x: number; y: number; isUserInput: boolean; value: number };
typesディレクトリで定義

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/utils/formatOpenCells.ts
> +import { userIdParser } from '../../../server/service/idParsers';
serverがclientと共有して良いのは型のみ

commonTypesWithClientのみが共有できる場所

queryの文字列がuserIdであることをclientは確かめる方法がないためParserを使ってはいけない

aspidaのresBodyにUserIdを指定してserverからuserIdをもらえばstringにならずに済む

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/utils/formatOpenCells.ts
> +    .map((cell) => JSON.parse(cell))
このあたりの処理ややこしいのだが、openCellsをコピーしている？

最後のmapで展開しているからコピーの必要性がない

2023-08-21 21:05 UTC, bondrewd-iniad commented on client/src/utils/formatOpenCells.ts
> +      whenOpened: new Date().getTime(),
近代のTSは極力関数で記述することが望ましいので Date.now()

2023-08-21 21:09 UTC, bondrewd-iniad commented
コントローラーのデザインが利用シーンにマッチしていない

コントローラーそのものであるスマホの画面内にさらにコントローラーを描画するのは不自然

PCでアクセスしたらコントローラー風に切り替えるならわかる

無限ボードらしくスマホ全体をボード描画に使い、前面に各種ボタンを配置するのがよい

2023-08-21 21:11 UTC, bondrewd-iniad commented
「PCでアクセスしたらコントローラー風に切り替えるならわかる」と書いたが、実際PCアクセスを想定していないので切り替え処理をする妥当性はない

2023-08-21 22:37 UTC, yossuli commented on client/src/utils/formatOpenCells.ts
> +    .map((cell) => JSON.parse(cell))
どのあたりについて言及されているのかいまいち分からないので期待される回答と異なるかもしれません。
Set型で重複を取り除きたかったのですが、連想配列だと不可能だったためJSON型で比較してもとに戻しています。

2023-08-22 03:28 UTC, bondrewd-iniad requested changes

2023-08-22 03:28 UTC, bondrewd-iniad commented on client/src/utils/formatOpenCells.ts
> +    .map((cell) => JSON.parse(cell))
Setによる重複除外は連想配列のプロパティ順が整列していることを保証できる場合にしか使えない
以下は同じ座標だが順序が違うので除外されない

![image](https://github.com/INIAD-Developers/Mugen-sweeper/assets/85666399/550665d4-54b2-4da3-9375-25f2658aaa66)

2023-08-22 03:52 UTC, bondrewd-iniad requested changes

2023-08-22 03:52 UTC, bondrewd-iniad commented on server/useCase/playerUseCase.ts
> +  getStatus: async (playerId: string) => await playersRepository.find(userIdParser.parse(playerId)),
useCaseでstring -> branded への変換を保証できない
DBを通して存在確認できた場合にbranded IDとしてパースできる

server/commonTypesWithClient/branded.ts に Maybe型を導入しfindはMaybeを受け取るようにするとフロントにUserId型を強制しつつ、バックエンドではMaybe<UserId>を受け取れる

```ts
export type Maybe<T> = T | Branded<'Maybe'>;
```

```ts
export const playersRepository = {
  find: async (id: Maybe<UserId>)
```

2023-08-22 03:52 UTC, bondrewd-iniad commented on server/useCase/playerUseCase.ts
> +  getStatus: async (playerId: string) => await playersRepository.find(userIdParser.parse(playerId)),
userIdParserという名前でplayerIdをパースしていて混乱する

2023-08-22 03:52 UTC, bondrewd-iniad commented on client/src/utils/formatOpenCells.ts
> +    .map((cell) => JSON.parse(cell))
全体のロジックを見ていないが、そもそも重複が発生しないようにできないのだろうか

ゲーム全体としてopenCellsが重複するという知識を共有できるだろうか

2023-08-22 03:52 UTC, bondrewd-iniad commented on client/src/pages/game/index.page.tsx
> +  const board: BoardModel = minesweeperUtils.makeBoard(bombMap, userInputs);
makeBoardのreturn型がBoardModelならアノテーション不要

2023-08-22 04:04 UTC, bondrewd-iniad requested changes

2023-08-22 04:04 UTC, bondrewd-iniad commented on client/src/components/Button/index.page.tsx
> +  gridRowColumn: number[];
外から見て数値4つ必要だとわからないし順番も不明瞭

grid: { rowStart: number, rowEnd: number, columnStart: number, columnEnd: number }

なら初見で使い方がわかる
記述は冗長だが、みんなが使うユーティリティコンポーネントはこのくらいの配慮が必要

2023-08-22 04:04 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.module.css
> +  /* background-color: #f008; */
このコメントはどういう意図か？

他の人が作業するとき扱いに困る

2023-08-22 04:04 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +  const [currentPlayerPos, setPlayerPos] = useState<number[]>();
このファイル内でのみ扱う型としてPlayerPosをタプルで定義する

```ts
type PlayerPos = [number, number]
```

2023-08-22 04:04 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +  }, [player.x, player.y, board, currentPlayerPos]);
```ts
const displayPos = useCallback((): PlayerPos =>
    currentPlayerPos !== undefined && board[player.y][player.x] === -1
       ? currentPlayerPos
       : [player.x, player.y];
```

2023-08-22 04:29 UTC, yossuli commented on server/useCase/playerUseCase.ts
> +  getStatus: async (playerId: string) => await playersRepository.find(userIdParser.parse(playerId)),
今後ほかの、関数などの命名の最適化を行うさいにまとめて変更します

2023-08-22 06:21 UTC, bondrewd-iniad requested changes

2023-08-22 06:21 UTC, bondrewd-iniad commented on client/src/pages/controller/index.page.tsx
> +            <button className={`${styles.button} ${styles['open-button']}`} onClick={() => dig()}>
frag -> flag
onClick={frag}
onClick={dig}

2023-08-22 06:21 UTC, bondrewd-iniad commented on client/src/utils/formatOpenCells.ts
> +    .map((cell) => JSON.parse(cell))
他を見たが、重複除外はdig関数の責務に見える

重複状態は不正なはずで、そのまま状態に格納してはいけない

2023-08-22 07:28 UTC, bondrewd-iniad requested changes
11時間前のコメント一つと、コントローラーのデザインについても未解決

2023-08-22 07:28 UTC, bondrewd-iniad commented on client/src/pages/controller/index.page.tsx
> +    typeof router.query.playerId === 'string' ? (router.query.playerId as Maybe<UserId>) : null;
serverからplayerIdを受け取ることでasやパーサーを回避するIssueを作るべき

2023-08-22 12:20 UTC, bondrewd-iniad requested changes

2023-08-22 12:20 UTC, bondrewd-iniad commented on client/src/components/GameDisplay/GameDisplay.tsx
> +  }, [player]);
@yossuli 
これどうなったの？

2023-08-22 12:23 UTC, yossuli commented
@bondrewd-iniad 
changesのタブから見ると[player.x,player.y]に修正済みなのですが、こちらの表示には反映されないのです
コンポーネントに渡される度に発火するのは意図していないため、上記のように修正してあります

2023-08-22 12:26 UTC, bondrewd-iniad commented
@yossuli 
リポジトリそのものを見に行ったけど反映されてないぞ？
https://github.com/yossuli/Mugen-sweeper/blob/front/client/src/components/GameDisplay/GameDisplay.tsx#L13

![image](https://github.com/INIAD-Developers/Mugen-sweeper/assets/85666399/471b5190-9b5b-4dff-a2be-d7e7c5add6c3)

2023-08-22 12:45 UTC, yossuli commented
@bondrewd-iniad 
具体的に何行目のことを指しているか教えていただきたいです。
僕としては3個上のコメントにおける12行目`set...({x:player.x,y:player.y})`を`set...([player.x,player.y])`とするように、という指摘と捉えていて、その点については変更済みであると認識しています。

2023-08-22 12:48 UTC, bondrewd-iniad commented
@yossuli 
useEffectの依存配列について指摘していたのでひとつ前のコメント内リンクの通り13行目を指している

2023-08-22 12:49 UTC, bondrewd-iniad commented
さらに言うと指摘行に色が付くようにリンクしてあった

2023-08-22 13:02 UTC, yossuli commented
@bondrewd-iniad お手数をおかけしました
修正しました

2023-08-22 13:52 UTC, bondrewd-iniad approved these changes
LGTM
お疲れ様でした

2023-08-22 13:53 UTC, merged